### ISSUE TITLE
Trying to test a composable that uses a composable

### ISSUE THREAD

**Issue by joerattz** [ktsn/vue-composable-tester#4]
I'm trying to test my composable that uses/wraps a PrimeVue toast composable.

Here is some relevant code from my composable:

```
import { useToast } from "primevue/usetoast";

export default () => {
    const pv_toast = useToast();

    const toast = (message: ToastMessageOptions) => {
        pv_toast.add(message);
    }

    return {
        toast: toast,
    }
}
```

Then in my test I'm doing this:

```
import { mount } from 'vue-composable-tester'
import useToast from "@/client/composables/useToast";  // This is my composable

describe('Testing useToast composable...', () => {
    let toast;

    beforeAll(() => {
        const { toast } = mount(() => useToast())
    });

    test('The success toast rendered', () => {
        toast.toastSuccess('You\'re on your way!', 'Yeah!');
    });
});
```

I'm getting this error:

```
   [Vue warn]: injection "Symbol()" not found.
      at <Anonymous ref="child" >
      at <App>

      4 |
      5 | export default () => {
    > 6 |   const pv_toast = useToast();
        |                    ^
      7 |
      8 |   const success = (detail: string, summary?: string) => toast({severity: ToastSeverity.SUCCESS, summary: summary, detail: detail});
      9 |   const info = (detail: string, summary?: string) => toast({severity: ToastSeverity.INFO, summary: summary, detail: detail});

      at warn (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6482:17)
      at Object.inject (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1185:13)
      at useToast (node_modules/primevue/usetoast/usetoast.cjs.js:10:31)
      at _default (src/client/composables/useToast.ts:6:20)
      at tests/client/componsables/useToast.spec.js:10:5
      at setup (node_modules/vue-composable-tester/lib/mount.js:44:28)
      at callWithErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6599:22)

  console.warn
    [Vue warn]: Unhandled error during execution of setup function
      at <Anonymous ref="child" >
      at <App>

      at warn (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6482:17)
      at logError (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6656:9)
      at handleError (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6648:5)
      at callWithErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6602:9)
      at setupStatefulComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6225:29)
      at setupComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6181:11)
      at mountComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4046:13)

  Testing useToast composable...
    × The success toast rendered

  ● Testing useToast composable... › The success toast rendered

    No PrimeVue Toast provided!

      4 |
      5 | export default () => {
    > 6 |   const pv_toast = useToast();
        |                    ^
      7 |
      8 |   const success = (detail: string, summary?: string) => toast({severity: ToastSeverity.SUCCESS, summary: summary, detail: detail});
      9 |   const info = (detail: string, summary?: string) => toast({severity: ToastSeverity.INFO, summary: summary, detail: detail});

      at useToast (node_modules/primevue/usetoast/usetoast.cjs.js:12:15)
      at _default (src/client/composables/useToast.ts:6:20)
      at tests/client/componsables/useToast.spec.js:9:35
      at setup (node_modules/vue-composable-tester/lib/mount.js:44:28)
      at callWithErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6599:22)
      at setupStatefulComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6225:29)
      at setupComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6181:11)
      at mountComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4046:13)
      at processComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4021:17)
      at patch (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3627:21)
      at ReactiveEffect.componentUpdateFn [as fn] (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4161:21)
      at ReactiveEffect.run (node_modules/@vue/reactivity/dist/reactivity.cjs.js:164:29)
      at setupRenderEffect (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4280:9)
      at mountComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4063:9)
      at processComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4021:17)
      at patch (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3627:21)
      at render (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4765:13)
      at mount (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3146:25)
      at Object.app.mount (node_modules/@vue/runtime-dom/dist/runtime-dom.cjs.js:1521:23)
      at mountV3 (node_modules/vue-composable-tester/lib/mount.js:52:20)
      at mount (node_modules/vue-composable-tester/lib/mount.js:7:11)
      at tests/client/componsables/useToast.spec.js:9:23
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)

```

The test is failing with this error message: ***No PrimeVue Toast provided!***

I don't really understand why that's the case since my composable imports it.  I get the sense that I could mock/inject it but I don't want to do that.  I'm trying to test that my composable interfaces with the embedded primevue toast composable properly.  So I don't want it mocked.  I also don't want to create a real primevue toast composable inside the test.  I want to rely on my composable importing and using it properly.

Any help or guidance would be appreciated.

**Comment by wobsoriano** [comment]
Once I need plugins when testing composables I go back to using `@vue/test-utils` and just create a reusable function that recreates the `mount` function of this library.

```ts
import { mount } from '@vue/test-utils'
import { defineComponent, h } from 'vue'
import ToastService from 'primevue/toastservice'
import useToast from '@/client/composables/useToast' 

function renderComposable<T>(composable: () => T) {
  const App = defineComponent({
    setup() {
      const result = composable()
      return result
    },
    render() {
      return h('<div />')
    }
  })

  const wrapper = mount(App, {
    global: {
      plugins: [ToastService]
    }
  })

  return wrapper
}

describe('toast', async () => {
  test('The success toast rendered', () => {
    const { vm } = renderComposable(() => useToast())
    vm.toastSuccess()
  });

  test('The error toast rendered', () => {
    const { vm } = renderComposable(() => useToast())
    vm.toastError()
  });
})
```
